### ISSUE TITLE
Additional 2 positions request

### ISSUE THREAD

**Issue by cycle4passion** [XMCQCX/NotifyClass-NotifyCreator#4]
Thanks for a great tool and I respectful request this feature.

I wanted to have ability to have 2 additional positions, lc=left center, and rc=right center. haven't pieced through the multi-monitor code to make sure this is accurate, but something like....

```ahk
      case 'lc': 
      {
        if minMaxPosY = monWATop
          gPos := 'x' monWALeft + m['padX'] ' y' (monWATop + (monWAheight / 2) - (gH / 2)) + m['padY']
        else
          gPos := 'x' monWALeft + m['padX'] ' y' (monWATop + (monWAheight / 2) - (gH / 2)) + this.padH
      }

      case 'rc': 
      {
        if minMaxPosY = monWATop
          gPos := 'x' monWARight - m['padX'] - gW ' y' (monWATop + (monWAheight / 2) - (gH / 2)) + m['padY']
        else
          gPos := 'x' monWARight - m['padX'] - gW ' y' (monWATop + (monWAheight / 2) - (gH / 2)) + this.padH
      }
```

**Comment by XMCQCX** [comment]
@cycle4passion
Thanks for the feedback. I've incorporated it into my test version. The code needs further modification in 3-4 additional places. I won't merge it into this version as I need to do more testing. It will probably be included in the next version if I manage to release it. Subscribe to the repo if you want to be notified if other versions are released.
