### ISSUE TITLE
multi monitor issues 

### ISSUE THREAD

**Issue by armanbinbashar** [XMCQCX/NotifyClass-NotifyCreator#5]
how to show the notification in working monitor automatically?
Notify.Show(,"test text",,,,'POS=CT TF=Impact TS=18 MON=2 TC=black MC=black BC=White SHOW=fade Hide=fade@250')

**Comment by XMCQCX** [comment]
@armanbinbashar If no monitor is specified, the display will default to the primary monitor using the MonitorGetPrimary() function.
https://www.autohotkey.com/docs/v2/lib/MonitorGetPrimary.htm

If you want it to appear on the monitor you're currently using, meaning the one where the active window is located. try this:
```
Notify.Show('My Title', 'The quick brown fox jumps over the lazy dog.',,,, 'mon=' MonitorGetWindowIsIn('A'))

MonitorGetWindowIsIn(winTitle)
{
    WinGetPos(&posX, &posY, &WinW, &WinH, winTitle)    
    centerWinX := posX + WinW/2
    centerWinY := posY + WinH/2

    Loop MonitorGetCount() {
        MonitorGet(A_Index, &monLeft, &monTop, &monRight, &monBottom)
        if (centerWinX >= monLeft) && (centerWinX < monRight) && (centerWinY >= monTop) && (centerWinY < monBottom)
            return A_Index
    }

    return 0
}
```

**Comment by armanbinbashar** [comment]
thank you for the on-spot reply
