### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by H5820121** [XMCQCX/NotifyClass-NotifyCreator#6]
Your script is great, it's exactly what I was looking for!
I have a few questions:
1. How can you define .OnEvent('Escape', (gui) => gui. Destroy()) for example for Notify.Show('The quick brown fox jumps over the lazy dog.',,,,, 'dur=4 pos=tc')
?
2. I saw that you use rounding corners, I would be very grateful if you could explain to me how to do this, for example in my script there is 
MyMsg := Gui('+AlwaysOnTop -Caption +Disabled -SysMenu +Owner +Border'), MyMsg.SetFont('s11',"Segoe UI Semibold")
MyMsg.BackColor := '0xfffcde'
MyMsg.AddText 'Center', 'MY MSG'
MyMsg.Show

Could you please write me a script that will round the corners of MyMsg GUI?
Many thanks!

**Comment by XMCQCX** [comment]
@H5820121 I've posted a response on the forum.

**Comment by H5820121** [comment]
Thank you, the scripts you gave are great!
Does Notify.ahk have an option like DrawBorderRound(hwnd, color)?

‫בתאריך יום ב׳, 9 בספט׳ 2024 ב-22:15 מאת ‪XMCQCX‬‏ <‪
***@***.***‬‏>:‬

**Comment by XMCQCX** [comment]
@H5820121 No, it's not in the current version (1.6.0). It's included in my test version and will likely be in the next version if I manage to release it. Subscribe to the repo to be notified when new versions are released.

**Comment by H5820121** [comment]
I wish good luck!, we are all looking forward to it.

‫בתאריך יום ב׳, 9 בספט׳ 2024 ב-23:38 מאת ‪XMCQCX‬‏ <‪
***@***.***‬‏>:‬

**Comment by H5820121** [comment]
@XMCQCX
@nperovic has developed a script that applies to the GUI the effects of
WIN11 Acrylic and Mika
https://github.com/nperovic/GuiEnhancerKit/issues/4#issuecomment-2348173995
Maybe you can use this in the new version for Notify.ahk.
Thanks!

‫בתאריך יום ב׳, 9 בספט׳ 2024 ב-23:38 מאת ‪XMCQCX‬‏ <‪
***@***.***‬‏>:‬

**Comment by XMCQCX** [comment]
@H5820121 Thanks for letting me know. That seems interesting. I’ll check it out.

**Comment by H5820121** [comment]
@XMCQCX
I saw you were using animation.
I have  AHK GUI for example myGui := Gui("-Caption").
I rounded its corners by FrameShadow(myGui.hwnd)
How can I make to it an FADE 225 or 250 animation?
I would be very grateful if you could write me a AHK V2 script for this.
Thank you!


‫בתאריך יום ב׳, 9 בספט׳ 2024 ב-22:15 מאת ‪XMCQCX‬‏ <‪
***@***.***‬‏>:‬
