### ISSUE TITLE
New option 

### ISSUE THREAD

**Issue by H5820121** [XMCQCX/NotifyClass-NotifyCreator#7]
Thanks for the great script!
You can also add an option to destroy Notify when the user does some activity, something like this:

DestroyInUserInput() {
    global
    prevTimeIdle := A_TimeIdle
   SetTimer waitForActivity, 20

    waitForActivity() {
        global
        if (prevTimeIdle <= A_TimeIdle) {
            return
        }
        ; Otherwise:
        Notify.DestroyAll()
        SetTimer , 0  ; i.e. the timer turns itself off here.
    }

}
Based on https://www.autohotkey.com/boards/viewtopic.php?p=589192#p589192
By the way, I subscribe here with you to announce new versions, and I have not received any notification about the new version, could you please arrange this in the future?

**Comment by XMCQCX** [comment]
@H5820121 I've posted a response on the forum.
